---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming
  namespace: big-data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      containers:
        - name: spark-streaming
          image: asia-northeast1-docker.pkg.dev/robust-magpie-479807-f1/my-repo/spark-streaming:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "football-stream"  # Sửa lại cho đúng topic của Producer
            - name: ELASTICSEARCH_NODES
              value: "elasticsearch"
            - name: ELASTICSEARCH_INDEX
              value: "football-matches" # Sửa lại cho đúng index Dashboard tìm
            - name: CASSANDRA_HOST
              value: "cassandra"         # Dùng tên service ngắn gọn cho ổn định
          resources:
            requests:
              memory: "256Mi" # Giảm từ 512Mi để dễ tìm node trống
              cpu: "100m"
            limits:
              memory: "1Gi"   # Giữ nguyên để Spark có chỗ thở khi xử lý
              cpu: "500m"
